### ISSUE TITLE
Can I use other login ways ?

### ISSUE THREAD

**Issue by reconlabs-luke** [kubeflow/dashboard#7]
I wanna use some login process not using Dex (Kubeflow's default) like OAuth

Could you guys guide something to use ?

**Comment by thesuperzapper** [comment]
@reconlabs-luke This will depend on which distribution of Kubeflow you are using.

For example, if you are using deployKF, you can easily connect it to almost anything (but you will still be using dex indirectly):

- https://www.deploykf.org/guides/platform/deploykf-authentication/#external-identity-providers

**Comment by juliusvonkohout** [comment]
Yes, you can use connector in Dex or connect ouath2 directly to your IDP see https://github.com/kubeflow/manifests/tree/master/common/oauth2-proxy#change-the-default-authentication-from-dex--oauth2-proxy-to-oauth2-proxy-only

/close
